### ISSUE TITLE
Mercurial not putting the proper path in for a source control picker

### ISSUE THREAD

**Issue by tijntacke** [Inedo/bmx-mercurial#6]
My solution file lives in the following location in BitBucket:
 
![img1](https://f.cloud.github.com/assets/6769608/2243988/11a60aa2-9d37-11e3-9940-e2a742dd60d7.png)

If I select the solution file and click the “Select” button followed by “Next” I get this error:
 
![img2](https://f.cloud.github.com/assets/6769608/2243992/1b715c4e-9d37-11e3-9f96-8ca4f3a6715d.png)

The path to the solution file generated by BuildMaster is:
bitbucket.org_clade_clade.buildmaster|default:Clade.BuildMaster.sln

I had to manually change this to bitbucket.org_clade_clade.buildmaster|default:src/Clade.BuildMaster.sln
to get this to work.

**Comment by kharnagy** [comment]
whoops fixed long ago
